### ISSUE TITLE
Build error -- Trying to scan non-existant directory

### ISSUE THREAD

**Issue by stormbytes** [AdamMagaluk/leo#31]
→ leo build -b uno
Cleaning build directory
Creating new build directory
Building basic as excutable.
/Applications/Arduino.app/Contents/Java/hardware/arduino/cores/arduino
/usr/local/lib/node_modules/leo/lib/dirscan.js:25
    throw new Error('Tried to directory scan a non-existant directory');
          ^
Error: Tried to directory scan a non-existant directory
    at dirscan (/usr/local/lib/node_modules/leo/lib/dirscan.js:25:11)
    at LeoBuild.buildMain (/usr/local/lib/node_modules/leo/lib/build.js:79:19)
    at /usr/local/lib/node_modules/leo/lib/build.js:69:10
    at Object.async.eachSeries (/usr/local/lib/node_modules/leo/node_modules/async/lib/async.js:130:20)
    at LeoBuild.build (/usr/local/lib/node_modules/leo/lib/build.js:57:9)
    at Command.run (/usr/local/lib/node_modules/leo/commands/build.js:40:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/leo/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/leo/node_modules/commander/index.js:477:12)
    at Command.parse (/usr/local/lib/node_modules/leo/node_modules/commander/index.js:370:21)

**Comment by stormbytes** [comment]
Is this project still being maintained?

**Comment by AdamMagaluk** [comment]
Are you currently in a directory with source files or a package.json? What OS?

If you run `leo new Blink` and `cd Blink` and `leo build -b uno` does that work?

As far as maintained, not actively anymore I will try to fix small blatant errors if they are reported.

**Comment by stormbytes** [comment]
I'm on Mac OSX 10.7. Tried your suggestion -- no difference (see output below).

Looks to me like the problem might be the very first line after "Buidling basic as executable" 

=> /Applications/Arduino.app/Contents/Java/hardware/arduino/cores/arduino
/usr/local/lib/node_modules/leo/lib/dirscan.js:25

That path isn't valid --- 

Closest thing to it would be:

/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino

Is there a central config file for this package or is it hard-coded into the build script?

-------------------------------------------------------
Output
-------------------------------------------------------

→ leo new foo
→ cd foo
→ leo build -b uno
Cleaning build directory
Creating new build directory
Building basic as excutable.
/Applications/Arduino.app/Contents/Java/hardware/arduino/cores/arduino
/usr/local/lib/node_modules/leo/lib/dirscan.js:25
    throw new Error('Tried to directory scan a non-existant directory');
          ^
Error: Tried to directory scan a non-existant directory
    at dirscan (/usr/local/lib/node_modules/leo/lib/dirscan.js:25:11)
    at LeoBuild.buildMain (/usr/local/lib/node_modules/leo/lib/build.js:79:19)
    at /usr/local/lib/node_modules/leo/lib/build.js:69:10
    at Object.async.eachSeries (/usr/local/lib/node_modules/leo/node_modules/async/lib/async.js:130:20)
    at LeoBuild.build (/usr/local/lib/node_modules/leo/lib/build.js:57:9)
    at Command.run (/usr/local/lib/node_modules/leo/commands/build.js:40:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/leo/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/leo/node_modules/commander/index.js:477:12)
    at Command.parse (/usr/local/lib/node_modules/leo/node_modules/commander/index.js:370:21)
→
